### ISSUE TITLE
Use of `embedded_hal_0_2` to obtain required I2c traits for I2cDriver

### ISSUE THREAD

**Issue by bsodmike** [esp-rs/esp-idf-hal#172]
Please refer to https://github.com/esp-rs/esp-idf-hal/blob/master/src/i2c.rs#L314-L388. I found that I would get such errors when using `shared-bus` with `I2cDriver`

```rust
151 |     i2c_proxy1.write();
    |                ^^^^^ method not found in `I2cProxy<'_, NullMutex<I2cDriver<'static>>>`
    |
   ::: /home/mdesilva/.cargo/registry/src/github.com-1ecc6299db9ec823/embedded-hal-0.2.7/src/blocking/i2c.rs:165:8
    |
165 |     fn write(&mut self, address: A, bytes: &[u8]) -> Result<(), Self::Error>;
    |        ----- the method is available for `I2cProxy<'_, NullMutex<I2cDriver<'static>>>` here
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
4   | use embedded_hal::blocking::i2c::Write;
```

By digging through the source I found use of `embedded_hal_0_2`.  To fix this I had to add add `use embedded_hal_0_2::prelude::*;` and include `embedded-hal-0-2 = { package = "embedded-hal", version = "0.2.7", features = ["unproven"] }` into my Cargo TOML.

With the upcoming release of new crates, I think we should fully say goodbye to the older version of embedded_hal and just move those traits into the new version.  Thoughts?

**Comment by ivmarkov** [comment]
I hope the explanations in the Matrix channel has clarified the situation a bit. Again: I don't think the fact that `esp-idf-hal` implements the traits from both hals (e-hal 1.0-aphpa9 and e-hal 0.2) is bad. Quite the opposite - it enables extra flexibility.

By the way, the `shared-bus` crate [does the same](https://github.com/Rahix/shared-bus/blob/main/Cargo.toml#L27). It is only that they did not update their e-hal 1.0 dep from -alpha8 to -alpha9, possibly because they got tired tracking the alpha releases and hope e-hal 1.0 release is imminent. Which of course means that shared-bus and esp-idf-hal are currently NOT compatible w.r.t. e-hal 1.0 (as -alpha releases are not compatible with each other). But they are still compatible via e-hal 0.2, which is not your problem and in fact is saving you. Your problem is the alpha incompatibility.
