### ISSUE TITLE
esp-idf-hal will support the embedded-hal timer traits?

### ISSUE THREAD

**Issue by jmmb13** [esp-rs/esp-idf-hal#230]
Hello,

Does esp-idf-hal is planning to support embedded-hal::timer traits in TImerDriver?

Thank you!
jmmb

**Comment by Vollbrecht** [comment]
I think they are no current plan's for it. This is manly because the embedded-hal timer was axed in the current itterations of the embedded-hal 1.0.0.alpha releases. So i think we don't want to add api's that currently are already deprecated. If they are plan's in the 1.0.0.alpha release or on master branch for timer specific traits, we will support such things for sure. Its a though position with the alpha traits currently.

**Comment by Vollbrecht** [comment]
for more info and tracking look here: https://github.com/rust-embedded/embedded-hal/issues/359
