### ISSUE TITLE
Broken docs for Gpio23

### ISSUE THREAD

**Issue by VorpalBlade** [esp-rs/esp-idf-hal#243]
According to rust-analyzer I'm getting a Gpio23 object (which makes sense, I'm trying to hook up a LED to that GPIO for a test). When I try to find documentation for it however at https://esp-rs.github.io/esp-idf-hal/esp_idf_hal/gpio/index.html it only goes up to Gpio21!?

I presume this is due to this docs being built for a different module, but on docs.rs there is a dropdown to switch between build targets. It would be really useful to have that here.

For context: I'm using and targeting a traditional Xtensa ESP32 module (ESP32-WROVER-IE specifically on a ESP32-DevKitC, this was the only dev board with I2S support and traditional non-LE Bluetooth I could find in stock here in Sweden).

(At least it is possible to build the docs locally with `cargo doc`)

**Comment by Vollbrecht** [comment]
The hosted docu is build with the riscv target. docs.rs doesn't have support to cross-compile code for rust tier3 targets that need support of the "Zbuild-std"  feature. Additional problems arises with the way esp-idf-sys bindings are build and the underlying build process. That's why we have this github pages docs as a bandgap solution till we get it sorted out. Though building it locally is in your case a method to go.
