### ISSUE TITLE
Are there any examples of async http client?

### ISSUE THREAD

**Issue by lz1998** [esp-rs/esp-idf-hal#341]

**Comment by ivmarkov** [comment]
Zheng - why don't you join the Matrix room rather than opening issues with questions here? :)

Anyway. The ESP IDF HTTP client *seems* to maybe support non-blocking IO, but we don't support that yet.

I think it would be better if we just work on the `edge-net` HTTP client and make it work. Or you can just try/use this one: https://github.com/drogue-iot/reqwless
