### ISSUE TITLE
ESP32C3 GPIO4 and GPIO5 not working

### ISSUE THREAD

**Issue by sehraf** [esp-rs/esp-idf-hal#9]
I'm an unable to control GPIO 4 and 5. Matrix user jessebraham was able to reproduce this.
Other GPIOs behave as expected (using the same code as for GPIO4 and 5)

**Comment by mtorromeo** [comment]
I've been going crazy with this issue for a while.
Unless I manually reset the pins, most of them don't work, not just GPIO 4 and 5

```rs
    unsafe {
        gpio_reset_pin(gpio_num_t_GPIO_NUM_6);
        gpio_reset_pin(gpio_num_t_GPIO_NUM_7);
        gpio_reset_pin(gpio_num_t_GPIO_NUM_10);
    }
```

once I do this, everything works as expected

**Comment by sehraf** [comment]
Thanks for the workaround :+1:

**Comment by JurajSadel** [comment]
Thank you @mtorromeo!

**Comment by jessebraham** [comment]
I believe that the `IO MUX` may not be being configured properly.

Referencing Table 5-2 in the ESP32-C3's TRM (v0.4) it seems that all the values in the `Reset` column correspond with GPIO functions, so that would explain why calling `gpio_reset_pin` fixes it.

However in `IO_MUX_GPIOn_REG` (Register 5.22 in TRM) we find:

> __IO_MUX_GPIOn_MCU_SEL__ Select IO MUX function for this signal. 0: Select Function 0; 1: Select
Function 1; etc. (R/W)

According to the register field diagram the reset value is `0`, or Function 0. Looking again at Table 5-2 we see that Function 0 is _not_ GPIO for the majority of pins.

Is it possible the default `IO MUX` config is causing some issue? I don't have the energy to investigate this right now but I can do some actual testing tomorrow and report back, just wanted to share my thoughts.

**Comment by 1c3t3a** [comment]
I experience the same issue with the LED (GPIO 8) on the esp32c3 Devkit M. For me even resetting doesn't change much, sometimes the LED goes on but not off and sometimes it doesn't work at all.

**Comment by 2asoft** [comment]
I also experience this on an older esp32 devkit, and the  workaround with resetting the pin helped.
The only pin that seems to have worked out of the box is io2, the rest required the workaround.

**Comment by ivmarkov** [comment]
@jessebraham - the ESP-IDF blinking LED sample seems to reset the pin prior to using it. Adding a pin reset code in the `into_output` / `'into_input` methods and so on might be an OK workaround?

**Comment by ivmarkov** [comment]
... and into the Pin::rest() method implementation perhaps as well.

**Comment by jessebraham** [comment]
Resetting the pin seems to resolve the issue based on my limited testing. I think this is a fine solution for now.

I have a fix ready to PR, I'm just going to do a bit more testing before I submit it.
